
export const ADD_DATA_POSTRES = 'ADD_DATA_POSTRES'
export const ADD_DATA_BEBIDAS = 'ADD_DATA_BEBIDAS'
export const ADD_DATA_PLATILLOS = 'ADD_DATA_PLATILLOS'

/* export const ADD_DATA_POSTRES = 'ADD_DATA_POSTRES'
export const ADD_DATA_CLIENTES = 'ADD_DATA_CLIENTES'
*/
