# Generated by Django 3.1.6 on 2021-02-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usuario',
        ),
        migrations.AddField(
            model_name='profile',
            name='usuario',
            field=models.CharField(choices=[('mesero', 'mesero'), ('cocinero', 'cocinero')], max_length=35, null=True),
        ),
    ]
