# Generated by Django 3.1.6 on 2021-02-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0002_auto_20210219_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clientes',
            field=models.ManyToManyField(to='clients.Cliente'),
        ),
    ]
